### ISSUE TITLE
error message - bad signature

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#100]
User Sudo tried to send TEA to other users, after typing in password of polkdot wallet, it error message appeared. It is not for wrong password as I tried to type wrong password, polkdot wallet gave me error message. Don't know why this happened. I happened to other users as well. 

![image](https://user-images.githubusercontent.com/12605218/125708337-7eccc2a2-826d-489a-be45-ecea986b7e09.png)

**Comment by liyangwood** [comment]
Pending, I will get some research about this error.

**Comment by liyangwood** [comment]
https://github.com/polkadot-js/apps/issues/4487

**Comment by liyangwood** [comment]
增加了一些log，如果继续发现此错误，请把console log中的内容截图给我帮助调试。

**Comment by lxm218** [comment]
close for now
