### ISSUE TITLE
Question: Can browser wallet turns to an Electron local app that can run without web server.

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#105]
If yes, the browser wallet can be a local dapp, either from Electron or IPFS static webapp. It doesn't need to communicate with a webserver, but to query indexer and layer 1 only.

**Comment by liyangwood** [comment]
Stop for now.
Summarize as below.
1. Can turn to a Electron desktop app.
2. But no polkadot's extension for the desktop app. 
3. Will reopen it when got the solution of how to sign for layer1 safely.

**Comment by liyangwood** [comment]
Just closed.
