### ISSUE TITLE
complete the UI text change request by the end of Wed

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#108]
We will need to have at least one full day for the UI text to change and one more day for testing. So in order to meet the Friday deadline, you have to complete all the change request by the end of Wed.

Although we can still change the UI text on the fly. (Because upgrade UI wallet webapp  do not need to restart blockchain), we are better to have most of them complete before open to public.

**Comment by geopor** [comment]
All done
