### ISSUE TITLE
auction start price not consistence

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#109]
the start price for this auction is 100 t. I put bid price as 100 t, it's success. Therefore, on this page, it should say 'You need at least 100 t to bid this auction'.  

![image](https://user-images.githubusercontent.com/12605218/126437177-0d74a67f-cde4-454d-9116-0519195d6827.png)

**Comment by liyangwood** [comment]
Check in client before send tx to layer1 when click confirm.
Can test after deployed with wallet version 0.0.10

**Comment by liyangwood** [comment]
deployed
