### ISSUE TITLE
Reward function is not working

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#114]
I withdraw reward for these 2 users and no more staking reward shown 

![image](https://user-images.githubusercontent.com/12605218/126571967-91e16795-5da5-4824-b6bc-253d50abc8b8.png)

![image](https://user-images.githubusercontent.com/12605218/126572009-b818b9a2-b09c-4dfd-a959-40a39a763482.png)

**Comment by liyangwood** [comment]
Please test with wallet version 0.0.9
