### ISSUE TITLE
User planted one CML with debt, he cannot put another CML into auction even though he has over 100 t balance

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#115]
In this case, user got debt because he planted one CML, he should be able to put other CML into auction if he has over 100 t balance
![image](https://user-images.githubusercontent.com/12605218/126683493-92fca9ef-fb6a-4b56-9eb8-6363b631b648.png)

**Comment by raindust** [comment]
implement in https://github.com/tearust/tea-camellia/commit/a9dbf10acfd9eee89bcf08701d16609ad313f8ee and https://github.com/tearust/tea-camellia/commit/57b15df1f1d54c56210c2619578021333c8624df .

@liyangwood here are some changes front side need to follow:
- pay_off_mining_credit extrinsic add `cml_id` paramter
- add "cml_userCreditList" rpc interface to query all credits of given user

**Comment by liyangwood** [comment]
done
Can test after deployed with wallet version 0.0.10

**Comment by kevingzhang** [comment]
hold this issue under your name for now. Once it is deployed and testable, assign it to tester
