### ISSUE TITLE
if user want to add high price for his current bid, price should be price he wants to bid instead adding xxx price

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#116]
用户的bid price被别人超过，他想追加的时候，页面显示的price应该是追加后的price，而不是追加那部分。 
![image](https://user-images.githubusercontent.com/12605218/126686427-04c62f8f-f242-4316-8223-dd03047d7e5d.png)

**Comment by liyangwood** [comment]
目前的逻辑是用户一旦bid，对应的price就会被lock了，在auction没有结束或没有手动remove之前是不会unlock的，上面这种情况，就是当别人bid超过我时，我之前的price依然是被lock的，所以只要继续增加追加的就可以了，如果是总共的bid price，那么用户被lock的price就会double了，不符合逻辑。
