### ISSUE TITLE
Bug - auction completed

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#117]
The bid was over but this user's page is not refreshed and he click +. In this case, it should show 'This auction is completed'. 

![image](https://user-images.githubusercontent.com/12605218/126687753-ed838338-c205-456f-a7f2-3399fed76a3f.png)

**Comment by liyangwood** [comment]
It is hard to judge in client.
is there any error returned in above situation?

**Comment by kevingzhang** [comment]
> It is hard to judge in client.
> is there any error returned in above situation?

@lxm218 Do you have an answer for @liyangwood 's question?

**Comment by kevingzhang** [comment]
@liyangwood since front end won't know it is completed before user send request, what you can do is that when the result get back from the backend, when it is negative number, do not show the negative number to users, just show an error message saying the auction has been completed XXX ago.

**Comment by kevingzhang** [comment]
please fix and move forward

**Comment by kevingzhang** [comment]
please fix and move forward. this issue has not been completed for too long

**Comment by liyangwood** [comment]
done with wallet version 0.0.27
