### ISSUE TITLE
make browser wallet into an IPFS package

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#121]
User can load it from any IPFS gateway.

Once done, add the CID and URL to launch in this issue and assign to @geopor He will write it into the tutorial

**Comment by liyangwood** [comment]
Done.
Latest url will be updated in https://github.com/tearust/tea-browser-wallet/blob/master/readme.md#deploy-to-ipfs

**Comment by kevingzhang** [comment]
from the url, QmZfSY3Ft74WdRMohmU9a5PatYp556RSevp1rGUeuLbjDc is the CID. Any IPFS gateway can load such CID to launch our wallet. But the IPFS is very slow, so it would be very common that you cannot see the wallet in "any" ipfs gateway.

**Comment by kevingzhang** [comment]
FYI, the ipfs package. not sure how to explain to our customers.

**Comment by kevingzhang** [comment]
I just noticed that started yesterday, the polkadot js browser extension won't work with HTTP. it requires https. in this case, the pure IPFS could not work

**Comment by geopor** [comment]
Ok I have removed the mention of running wallet from IPFS from both readme files. I think this issue can be closed.
