### ISSUE TITLE
Fix wording for genesis bank logic

### ISSUE THREAD

**Issue by liyangwood** [tearust/tea-browser-wallet#122]
<img width="1122" alt="WeChata68be3f98ed9c5828cb04e5a5c787870" src="https://user-images.githubusercontent.com/3214173/127757507-449a1fe5-c587-4d35-a1ff-1407fe6004bb.png">
<img width="1102" alt="WeChatf13769a95629cd680fae445b49e29169" src="https://user-images.githubusercontent.com/3214173/127757515-496d8698-90ab-4bcc-b145-3595235ff9e1.png">
<img width="1128" alt="WeChata5ce2e16ecb44ecf5b6d3121f53647b9" src="https://user-images.githubusercontent.com/3214173/127757546-4852ceef-bda9-4d66-ba00-3d77c020dfe6.png">

@geopor please fix the wording for the genesis bank logic. above was the main workflow for reference.

**Comment by geopor** [comment]
Hi Jacky 
My suggestions are:
<img width="1122" alt="1 Genesis bank" src="https://user-images.githubusercontent.com/86096370/127908574-430b45a8-31b5-4143-9f11-425e1de8be69.png">
<img width="1102" alt="2 Genesis bank" src="https://user-images.githubusercontent.com/86096370/127908577-6c056a15-b4d8-459d-b2ae-d90a9688aeeb.png">

1. **My collateral seeds**
(If that is too long and doesn't fit in header, can also use **My CML collateral**)
2. **deposit to genesis bank**
3. **Deposit CML to Genesis bank**
4. **Are you sure you want to deposit CML as collateral to Genesis bank?**
5. **payoff** is good for the last tooltip.

**Comment by liyangwood** [comment]
done with wallet version 0.0.18
