### ISSUE TITLE
based on your own experience on make the browser wallet work in your own computer, improve the readme

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#125]
https://github.com/tearust/tea-browser-wallet/blob/master/readme.md

the goal is that anyone wants to run the browser wallet locally can make it

**Comment by geopor** [comment]
Ideally IPFS method will be completed: https://github.com/tearust/tea-browser-wallet/issues/121

Then we'll have 3 to run wallet explained in the readme - local, IPFS, remote server

**Comment by kevingzhang** [comment]
Can @geopor improve the readme, leave the IPFS CID as a placeholder so that Jacky can fill up in the future.
Please commit your change, or a pull request if you cannot. Jacky only replace the placeholder when he is done

**Comment by geopor** [comment]
Updated provisionally here: https://github.com/tearust/tea-docs/blob/main/Try_the_demo/README.md

Images saved to **/res** so it will look like this when site is refreshed:

<img width="883" alt="Screen Shot 2021-01" src="https://user-images.githubusercontent.com/86096370/128242594-b9b13641-00a7-4a69-aefa-9c630633849f.png">

<img width="876" alt="Screen Shot 2021-02" src="https://user-images.githubusercontent.com/86096370/128242601-b192a01e-fd1b-458e-8acd-945d8f9ee5e8.png">

**Comment by geopor** [comment]
Before I update https://github.com/tearust/tea-browser-wallet/blob/master/readme.md

@kevingzhang  I have a question because I didn't do any of this:

// Copy .env.test.sample to .env.test
// Change your local layer1 url and the Server URL in .env.test file

And it ran successfully. If I have to do any of the above please clarify because I'm not sure what I should change in that config.

**Comment by kevingzhang** [comment]
for those text changes, you do not need to change the .env.test.sample. that is for any logic that used to send API call to the layer1 server. 
There used to be the faucet that require the layer1 URL to work. So you do not need to do this. and free feel to update the readme.

**Comment by geopor** [comment]
Ok updated in both places

**Comment by kevingzhang** [comment]
I will close this for now. but we will soon update all IP address to https://wallet.teaproject.org once it is completed.
