### ISSUE TITLE
add TEA token loan term agreement page

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#127]
![image](https://user-images.githubusercontent.com/12605218/128262990-46c80c45-ce41-4789-8bed-9e04762be097.png)

After click deposit loan, the user will see a page showing **TEA Token Loan Term Agreement**, in the bottom of this page, there's button: **I agree/ I do not agree**; when the users click **I agree**, the loan is completed. If the user clicks **I do not agree**, it turns back to previous page. 

**TEA Token Loan Term Agreement**
Deposit CML to use as collateral for a TEA token loan.
Each billing cycle is 1000 blocks long (approximately 100 minutes).
The interest rate for every billing cycle is 0.08%.
The loan term is 200,000 blocks, approximately 55 hours.
The current loan amount is 500T regardless of the type of seed used for collateral.
Loan Repayment
The borrower needs to repay the loan before the 200,000 block-term ends. If the full borrowed amount is not repaid by the end of the loan term, the loan is considered to be in default and the CML collateral will be liquidated.

The borrower can repay the loan at any time. If repaid before the end of the loan term, the adjusted loan term is equal to blockheight when repaid - blockheight at loan start. The adjusted loan term/billing cycle calculates the number of times the interest rate is applied. This number is always rounded up. The total interest on the loan is calculated as rounded number of billing cycles * interest rate * loan amount. The interest rate is 0.08%, and the loan amount from the Genesis bank is always 500T.

Return of Collateral
When the borrower has repaid the loaned amount + interest, their collateral CML seed will be returned to them. Both the primary loan amount and interest in TEA token that's been repaid will be burned.

**Comment by liyangwood** [comment]
done with wallet version 0.0.25

**Comment by lxm218** [comment]
see #132
