### ISSUE TITLE
cannot see other users and page is loading

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#128]
e.poch version 1.5
wallet version 0.0.18

![image](https://user-images.githubusercontent.com/12605218/128264587-08275c63-0601-4c96-9846-fb85718b253a.png)

![image](https://user-images.githubusercontent.com/12605218/128264754-11b4ee09-edaa-4f55-92ae-63a3cab97cde.png)

**Comment by liyangwood** [comment]
看着状态，你那边的layer1没有连上，header下面的黄色线条代表正在连接layer1中，连上了以后是绿色的。
这个可以在check以下，看看是不是网络联链接的问题。
