### ISSUE TITLE
Depositing CML to Genesis bank doesn't show up in collateral page

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#130]
<img width="1440" alt="Screen Shot 2021-08-05 at 4 16 55 PM" src="https://user-images.githubusercontent.com/86096370/128433580-71236445-5d85-4b7b-b554-157634bacd8e.png">

After depositing CML to Genesis seed bank, 
1. 500 TEA is deposited, that is good
2. The CML seed (CML ID 10) should show up here as collateral. Refreshing both the browser and the little green refresh button doesn't make it show either.

**Comment by liyangwood** [comment]
done with wallet version 0.0.25
