### ISSUE TITLE
UI language update for Genesis loans

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#132]
<img width="1127" alt="Screen Shot 2021-08-06 at 10 15 57 AM" src="https://user-images.githubusercontent.com/86096370/128548202-d74b3fa9-6efb-47db-9696-e46ac4021164.png">

- Should read: **Deposit for loan**

**Comment by geopor** [comment]
<img width="955" alt="Screen Shot 2021-08-06 at 11 16 42 AM" src="https://user-images.githubusercontent.com/86096370/128556129-94e9e513-30f8-4597-875e-2c05e599bacd.png">

1. Should read **Deposit CML for loan**
2. Should read **Are you sure you want to deposit CML as collateral for a Genesis loan?**
3. Cml should be capitalized: **CML**
4. Should read **TEA Token Loan Agreement**
5. Should read **Clicking confirm means you agree.**
6. Should read **TEA Token Loan Agreement**
7. The last sentence should become the second sentence. After moving the sentence,  it should read:

> Deposit CML to use as collateral for a TEA token loan.
The current loan amount is 500T regardless of the type of seed used for collateral.
Each billing cycle is 1000 blocks long (approximately 100 minutes).
The interest rate for every billing cycle is 0.08%.
The loan term is 200,000 blocks, approximately 55 hours.

**Comment by lxm218** [comment]
On the Agreement page, can we add radio button **I agree**; Then we don't need  **Click confirm means you agree** which is a bit odd

**Comment by liyangwood** [comment]
done with wallet version 0.0.27
