### ISSUE TITLE
UI update: Staking modal

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#135]
<img width="949" alt="Screen Shot 2021-08-06 at 12 22 27 PM" src="https://user-images.githubusercontent.com/86096370/128563000-81f42450-1a25-4a5a-9324-796065fea42d.png">

1. Should read **Stake**
2. The 2nd sentence should read **You should leave "CML to stake" empty if you're staking TEA.**
3. Should read **CML to stake**

**Comment by liyangwood** [comment]
done with wallet version 0.0.27

**Comment by geopor** [comment]
<img width="848" alt="Screen Shot 2021-08-07 at 1 05 04 PM" src="https://user-images.githubusercontent.com/86096370/128612652-ae681380-e6b0-46c9-897e-3e505ed448b6.png">

Try putting a newline so it doesn't line break the word across lines.

**Comment by liyangwood** [comment]
fix with wallet version 0.0.28
