### ISSUE TITLE
UX update for auction bidding

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#136]
<img width="936" alt="Screen Shot 2021-08-06 at 12 26 06 PM" src="https://user-images.githubusercontent.com/86096370/128566967-90074ced-a740-4c01-ab5d-563611a1c53e.png">

1. Now reads _kTEA_ , should just be **TEA**.
2. This auction had a _Buy now_ price of 1100T. Shouldn't there  be an option to **Buy it now** for that price?
3. The bidder for this auction bid 1200. After the user pressed confirm, the auction disappeared from the list. The CML seed did end up in the wallet and TEA was transferred to seller, but this would be confusing for the bidder. Suggestion: If bidder bids higher than **Buy now** price, then modal should ask **The buy it now price is xx. Would you like to buy it at that price?**

**Comment by liyangwood** [comment]
done with wallet version 0.0.27

**Comment by geopor** [comment]
<img width="849" alt="Screen Shot 2021-08-07 at 12 24 44 PM" src="https://user-images.githubusercontent.com/86096370/128612166-856f2a15-f6c5-47c1-9d62-19e2331068d8.png">

Should read **Buy it now for 1100 TEA**

**Comment by geopor** [comment]
<img width="1120" alt="Screen Shot 2021-08-07 at 12 26 22 PM" src="https://user-images.githubusercontent.com/86096370/128612200-5acabd24-d5b7-45f9-9937-52d50d3b58be.png">

When user clicks Add button to add to their bid, it should still read:
**Buy it now for 1100 TEA**

The Buy it now amount doesn't change if someone has an open bid.

**Comment by liyangwood** [comment]
@geopor 
For the above tip, when user already bid for an auction. the buy now price will show how many user only need to pay to the buy-now price. 
That means if an auction with buy-now price 1000, when user bid 200 before. then he will see the buy now price is 800.

So if buy now does not change even user already bid. when select the Buy it now checkbox, I concern user does not know how many he need to pay.

**Comment by geopor** [comment]
Also the following should read: **Insufficient bid amount**

<img width="977" alt="Screen Shot 2021-08-11 at 12 02 09 PM" src="https://user-images.githubusercontent.com/86096370/129088107-5b9b7c45-6e6b-4fbd-b84b-1baf518b14df.png">

**Comment by liyangwood** [comment]
done

**Comment by geopor** [comment]
Seeing this instead of actual buy it now price when wanting to bid on auction:

<img width="885" alt="Screen Shot 2021-08-12 at 11 27 59 AM" src="https://user-images.githubusercontent.com/86096370/129249601-ecdc6f2b-de5e-4a12-9f66-62f11381323f.png">

**Comment by liyangwood** [comment]
Stupid mistake. fixed.
