### ISSUE TITLE
UX update: tooltips for wallet

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#137]
<img width="1125" alt="Screen Shot 2021-08-06 at 11 45 28 AM" src="https://user-images.githubusercontent.com/86096370/128567597-13cf61fd-e279-4b29-962f-543f9972f3c3.png">

I suggest that we add tooltips for these two concepts to help users. 

1. **The balance locked in staking and auction selling or bidding.**
2. **Reward paid out for staking in CML-activated nodes. The first to plant a CML seed along with a 1000 TEA stake is considered the miner for that node.**

One issue I see is that users might not understand that we are often referring to the first CML seed planter a staker, so tooltip might help them understand that.

**Comment by liyangwood** [comment]
done with wallet version 0.0.27
