### ISSUE TITLE
Feature: Calculate evaluation leader board. This is in wallet UI. User can click refresh to get up to date leader information. This is also the winner board at the last

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#138]
This is an RPC call to the layer 1.
Layer 1 will run a computation to generate a leader board( based on the assets evaluation). 
When at the end of each epoch. We stop all TEA nodes which generate new blocks. Leave only the NYC TEA node alive. This node will stop at the last block as if it is a snapshot. The leader board will stop there as the winner board.

@geopor  FYI

@raindust you can work on the backend first, then assign to @liyangwood for frontend. then back to tester

**Comment by kevingzhang** [comment]
this feature depends on 
- the Genesis exchange

**Comment by raindust** [comment]
Done

**Comment by liyangwood** [comment]
done with wallet version 0.0.28
