### ISSUE TITLE
UI for Genesis exchange and leader board

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#139]
This is from @raindust 

今天实现了genesis exchange的功能，通过RPC统计所有资产的功能也实现了。 还没有来得及写单元测试明天继续。@Jacky 可以看看现有的接口是否足够，下面是接口的链接
https://github.com/tearust/tea-camellia/blob/main/pallets/genesis-exchange/src/lib.rs#L129-L184
https://github.com/tearust/tea-camellia/blob/main/pallets/genesis-exchange/rpc/src/lib.rs#L19-L31

Please continue complete the UI part.

**Comment by kevingzhang** [comment]
For the leader board, since it does not belong to any feature, we can put it on the header. or anywhere you think better.

Genesis Exchange could also be a standalone header and page.

**Comment by liyangwood** [comment]
done with wallet version 0.0.28
