### ISSUE TITLE
who is this guy, why is he so rich? is he sudo?

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#143]
![image](https://user-images.githubusercontent.com/1761809/128659177-91fd8a75-2db2-4066-a492-215411e3d439.png)

**Comment by kevingzhang** [comment]
we should skip sudo, genesis bank, or exchange accounts. they are not candidates. 
I remember @raindust code has a filter to filter out those non-candidates. why he is still there

**Comment by liyangwood** [comment]
this is my account, I use it to test.

**Comment by kevingzhang** [comment]
wow, you are a billionaire! I am happy to be your friend.

**Comment by kevingzhang** [comment]
remove this kind of account when we release to public. I will close it for now.
