### ISSUE TITLE
the error message need to improve

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#144]
![image](https://user-images.githubusercontent.com/1761809/128659488-d5a64adc-3cf7-43cd-b704-9314a3a6ba7d.png)

**Comment by geopor** [comment]
I'm not sure the context, but I believe in general this should read:
**Insufficient TEA for transaction.**

**Comment by liyangwood** [comment]
@geopor 
https://github.com/tearust/tea-browser-wallet/blob/master/src/assets/error.js
please convert to user language

**Comment by geopor** [comment]
Updated: https://github.com/tearust/tea-browser-wallet/commit/1900b62568a9fd9734ee859cb00cc256ffe56ca9

Duplicate issue: https://github.com/tearust/tea-browser-wallet/issues/153

This one can be closed.
