### ISSUE TITLE
Log / Reward Logs shows all reward, not the current users. this is incorrect

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#147]
![image](https://user-images.githubusercontent.com/1761809/128661241-76f577fa-4b6e-4d69-b647-7b68c77fdefa.png)

**Comment by liyangwood** [comment]
fixed with wallet version 0.0.29

**Comment by kevingzhang** [comment]
I tested, but the log page will load forever. This request has not completed 

GET wss://wallet.teaproject.org/wss HTTP/1.1
Host: wallet.teaproject.org
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Upgrade: websocket
Origin: https://wallet.teaproject.org
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _gid=GA1.2.987825665.1628481632; _ga=GA1.2.556435480.1628191819; _ga_P4F1B69NY2=GS1.1.1628525944.1.1.1628526439.0
Sec-WebSocket-Key: nFP0xrmM24p0C4yzekV4oA==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

**Comment by liyangwood** [comment]
it worked now.
