### ISSUE TITLE
"Withdrawing rewards is not allowed with a staking debt balance". I found this error message not very clear

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#150]
![image](https://user-images.githubusercontent.com/1761809/128661909-c2c8e283-8707-40ba-ae0a-605e480fe0ed.png)

Do you think we can improve this error message?

**Comment by geopor** [comment]
Change to read:
**Withdrawal not permitted while account has an active loan. First pay off any outstanding loans before withdrawing rewards.**

**Comment by liyangwood** [comment]
done.
