### ISSUE TITLE
I sell all my USD, but got error insufficient USD

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#152]
![image](https://user-images.githubusercontent.com/1761809/128739656-fd1093e6-3394-4acc-a662-c5d38fb65bc0.png)
I can see my USD account is  1000.9 USD, but when I sell all of them, I got this error

@liyangwood I guess this is backend issue, so I assigned to @raindust , but if it is a frontend issue, please take it

**Comment by kevingzhang** [comment]
One possible reason, please confirm @liyangwood , the amount in the UI is TEA not USD.

**Comment by raindust** [comment]
fixed in https://github.com/tearust/tea-camellia/commit/499ba4a8323cb5ee5fee0c4f6efc31c54e4ed244

**Comment by kevingzhang** [comment]
Still not fixed in new epoch. I created a new issue in backend https://github.com/tearust/tea-camellia/issues/38
close this issue for now. keep tracking on https://github.com/tearust/tea-camellia/issues/38

**Comment by raindust** [comment]
need discuss
