### ISSUE TITLE
BUG: USD/TEA TEA/USD modal dialogues

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#156]
Getting **Min amount** warning when it shouldn't be for both USD->TEA and TEA->USD:

<img width="837" alt="Screen Shot 2021-08-08 at 9 17 18 PM" src="https://user-images.githubusercontent.com/86096370/128786495-f06ad967-1fb4-4846-b034-bc964d44dafd.png">

<img width="1116" alt="Screen Shot 2021-08-09 at 4 19 05 PM" src="https://user-images.githubusercontent.com/86096370/128786499-71eea02f-546b-4f74-a96d-7d04bc9ff0c5.png">

**Comment by geopor** [comment]
Also for the following modal, instead of **Estimate**, it should read: **Estimated**

<img width="416" alt="Screen Shot 2021-08-08 at 9 18 02 PM" src="https://user-images.githubusercontent.com/86096370/128786497-fded1d5c-b415-4263-a57b-0259193aabc5.png">

**Comment by liyangwood** [comment]
done with wallet version 0.0.31
