### ISSUE TITLE
TEA/USD = 0.1534, this is not possible. 

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#157]
![image](https://user-images.githubusercontent.com/1761809/128897125-5d4c7095-33d9-4efe-a5e0-f884b05c1acf.png)
I am not sure is it a bug in frontend or backend. Most likely in backend. So I will assign to Jacky to verify, if it is at backend, send to @raindust

**Comment by lxm218** [comment]
when it's Exchange USD to TEA, it makes more sense to use exchange rate of xxx TEA/USD;
when it's Exchange TEA to USD, it makes more sense to use exchange rate of xxx USD/TEA;
![image](https://user-images.githubusercontent.com/12605218/128912074-a800915b-83ba-4912-becc-f78fc616757e.png)

**Comment by liyangwood** [comment]
please test again with wallet version 0.0.32

**Comment by kevingzhang** [comment]
the exchange still has problem. but this issue can be closed
