### ISSUE TITLE
I stake a CML into a slot, next time, I can see this CML again in the UI. it should not be shown since I cannot stake it again

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#160]
![image](https://user-images.githubusercontent.com/1761809/128902087-2bd3dd93-14ad-4040-ab70-9942e412ebfd.png)

**Comment by kevingzhang** [comment]
If I refresh, or re-enter this "Mining CML" page, it works as expected "not showing CML that already stake".
But we should consider the case that user did not refresh

**Comment by lxm218** [comment]
I found similar issue - if user doesn't refresh page manually, when auction ended, the seed doesn't shown in buyer's assets until he refresh the page.

**Comment by liyangwood** [comment]
fixed with wallet version 0.0.32
