### ISSUE TITLE
A CML life is 4 days long, but the Genesis Loan due day is 14 days, this makes no sense

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#162]
![image](https://user-images.githubusercontent.com/1761809/128918602-140a031d-5191-44f9-ae9a-15f45f94db60.png)

On possible bug is the calculation of due day is wrong. I am not sure, please take a look first.

**Comment by raindust** [comment]
update in https://github.com/tearust/tea-camellia/commit/7708cc4acbcf000fba65d68aeb3c72eee4006c41

**Comment by liyangwood** [comment]
fixed with wallet version 0.0.32
