### ISSUE TITLE
Collateral CML cannot be sold error message

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#169]
![image](https://user-images.githubusercontent.com/12605218/129088196-0eb116a8-f949-4192-9f9d-cd19d395262a.png)

**Comment by liyangwood** [comment]
This error means CML is not belong to you, could not put it to auction store.
So what do you want to change to ?

**Comment by lxm218** [comment]
这里需要增加一个判断，有两种情况，一种是你说得这个CML不是我的，可以保留这个error message
另外一种情况是这个CML是我的，但是我抵押成loan了，error message换成上图写的：This CML is in loan collateral and cannot be sold.

**Comment by liyangwood** [comment]
@raindust 
返回错误做个区别吧，如果是loan的换成另外一个error

**Comment by raindust** [comment]
update in https://github.com/tearust/tea-camellia/issues/41

**Comment by lxm218** [comment]
这个没有修改，还是原来的error msg

**Comment by raindust** [comment]
please re-verify
