### ISSUE TITLE
if I double click a button to start signature, I can reproduce this error: Too low priority

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#173]
![image](https://user-images.githubusercontent.com/1761809/129237851-a65f2988-fbd0-4433-93ea-c969cc64db4d.png)
That is become the signature window pop up twice, but user may not be noticed.
can we disable the button so that the second click won't pop up the sign window?

**Comment by liyangwood** [comment]
fixed with wallet version 0.0.36
