### ISSUE TITLE
Confirm: If a seed get to the end of life, how will happen now? will it stop mining?

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#175]
Please answer this question for both of you. 
we have not get the any seeds die yet, so I do not know what will happen.

**Comment by liyangwood** [comment]
@raindust 这里现在是怎么处理的？
理论上应该是CML状态变化了，不在是mining tree了吧

**Comment by raindust** [comment]
如果超过生命周期状态不会立马做变化（立即变化意味着每个区块都要扫描效率太低），如果已经死亡则当前staking窗口内不再有挖矿收益，窗口期结束之后从CmlStore中删除
