### ISSUE TITLE
Is Genesis bank burn collateral seeds, need to send public event and logged in the Indexer. 

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#178]
In case of burnning collateral seeds. (if the borrowers did not repay), the layer 1 should send event. 
the indexer will log it in public area so that people will know what just happened

FYI @liyangwood

**Comment by raindust** [comment]
implement in https://github.com/tearust/tea-camellia/commit/e37e34d64b050717e1c35d035a7491fac13e6f52 @liyangwood

**Comment by liyangwood** [comment]
done
