### ISSUE TITLE
exchange rates are wrong

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#180]
The multiplication of these two exchange rates should equals 1. The first screenshot wasn't correct. now it's back to normal(2nd screenshot), please check log

![image](https://user-images.githubusercontent.com/12605218/129399870-d972c780-91df-4a0c-959b-57c1406e9f10.png)

![image](https://user-images.githubusercontent.com/12605218/129400185-e680f717-4d52-4bea-b507-8c771a373bc4.png)

**Comment by liyangwood** [comment]
@raindust 
看下这个

**Comment by kevingzhang** [comment]
I found it is backend bug.
the rpc responses are:
{"jsonrpc":"2.0","result":"20409854014256","id":9999}  

and 

{"jsonrpc":"2.0","result":"21596558725417","id":9999}

**Comment by kevingzhang** [comment]
After I make a exchange transaction, the result get back to normal.

**Comment by raindust** [comment]
Still not figure it out, I will build a version that fixed all except this issue, and keep watching this error.  @kevingzhang

**Comment by lxm218** [comment]
it appeared again
![image](https://user-images.githubusercontent.com/12605218/129454951-bfb07dbe-76a3-42c4-b4ec-609b9906375f.png)

**Comment by kevingzhang** [comment]
Finally, I caught the log and RPC call when bug appears:
![image](https://user-images.githubusercontent.com/1761809/129461143-426cfe58-571f-4e76-8e78-6f0bded5b442.png)
![image](https://user-images.githubusercontent.com/1761809/129461148-4e350d18-927c-4a20-a0de-408deb1b99a9.png)

[cml_currentExchangeRate] result => 693342857570923,518369122735628,46597173809391497,34854478656657588,1624120199999999886865358167729236

**Comment by kevingzhang** [comment]
@raindust You can use this log to debug

**Comment by kevingzhang** [comment]
At this point, If I sell one TEA, I will get 693 USD. and I actually got 693 USD in my USD account!
After this transaction, I can see the RPC response:
![image](https://user-images.githubusercontent.com/1761809/129461402-72e9e74c-0db2-47f0-8f4f-2fd04c60781b.png)

**Comment by kevingzhang** [comment]
The K value is no longer 40k X 40k when the bug appears. it is 1624120..... 
I do not know how come it changes.
I will read your code to figure out soon

**Comment by kevingzhang** [comment]
Possible reason: https://github.com/tearust/tea-camellia/commit/ca35dc369237ecb6d9a540e4f7514869939d16b4#r54906566

And I also found https://github.com/tearust/tea-camellia/commit/2766f83559f9875256f7ce0ef2b5fd02925492d1#r54906602  No transaction protection.

Also, add additional check on USD*TEA=k will help, although it cannot stop the bug but will know the problem right after it happens.

**Comment by raindust** [comment]
fixed in https://github.com/tearust/tea-camellia/commit/3c11363a1f5019856b6937704bedc4a7969630d3
