### ISSUE TITLE
UX request: round to 2 decimal places

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#181]
Requesting that for any number amount related to USD and TEA we:

- treat it like currency and round to two decimal places: $99.99
- always have second decimal place, never drop just because it's zero: $99.90 is ok, not $99.9

Would be needed for My assets, Marketplace, and Leader board.

#### Here is Leader board showing last 0 digit currently being dropped off:

<img width="1116" alt="Screen Shot 2021-08-13 at 11 32 42 AM" src="https://user-images.githubusercontent.com/86096370/129404210-33311018-1f24-4936-af3a-233f958d34c5.png">

#### Here is loan pay back showing last 0 digit currently being dropped off:

<img width="654" alt="Screen Shot 2021-08-13 at 11 46 40 AM" src="https://user-images.githubusercontent.com/86096370/129405587-20fa3be5-464e-4822-90a0-46897c947b9c.png">

#### Here are the exchange buttons which can be adjusted to two decimal places:

<img src="https://user-images.githubusercontent.com/12605218/129399870-d972c780-91df-4a0c-959b-57c1406e9f10.png">

#### Here are asset values in wallet that can also be adjusted:

<img width="1042" alt="Screen Shot 2021-08-13 at 11 46 59 AM" src="https://user-images.githubusercontent.com/86096370/129405682-92033a83-1ff4-42c6-b49c-2be96dc01143.png">

I don't know if you can program this, but whole numbers can stay whole numbers without any decimals: $0 is good better than $0.00  ... $90 is good, better than $90.00

**Comment by kevingzhang** [comment]
after a discussion, I would like to push back this issue.
In many wallets more than 2 decimal was kept. In many cases, the gas is very small number that people may not see the change.

I consider this is not a high priority issue.
