### ISSUE TITLE
Bug: Defrost day is longer than lifespan of CML

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#182]
See picture:

<img width="1145" alt="Screen Shot 2021-08-13 at 11 41 57 AM" src="https://user-images.githubusercontent.com/86096370/129406241-1b3cc528-1fe5-4cec-92b0-52a5c9c9c521.png">

**Comment by kevingzhang** [comment]
I was trying to set type C seeds live for 12 months, half of the lifespan of type A and B. but the defrost schedule conflict with this lifespan. 
My solution is to turn back the lifespan of type C to 24 months. this is the same as type A and B.

**Comment by kevingzhang** [comment]
FYI @raindust

**Comment by kevingzhang** [comment]
If you agree, you can close it @raindust  
I have checked in the code change

**Comment by raindust** [comment]
agreed

**Comment by kevingzhang** [comment]
let me test if in the next epoch to make sure it is fixed
