### ISSUE TITLE
Cancelling bid: update modal dialog

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#183]
When user tries to cancel their existing bid:

<img width="1168" alt="Screen Shot 2021-08-13 at 11 42 50 AM" src="https://user-images.githubusercontent.com/86096370/129406933-458036f6-ad38-4da8-8494-922f5fce1621.png">

this modal dialog should read: **You can't delete this bid until someone bids higher**

**Comment by liyangwood** [comment]
done with wallet version 0.0.42
