### ISSUE TITLE
Bug: Cannot bid even though there's enough to cover bid

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#185]
**User has enough TEA in wallet:**

<img width="1127" alt="Screen Shot 2021-08-13 at 12 43 28 PM" src="https://user-images.githubusercontent.com/86096370/129424338-e1a18359-cfe5-4d9d-ab26-6746549f4086.png">

**But get a not enough error when trying to bid 501:**

<img width="1006" alt="Screen Shot 2021-08-13 at 12 43 11 PM" src="https://user-images.githubusercontent.com/86096370/129424337-e0be6da4-97e0-4dce-a757-f4ccfbb8578d.png">

**Comment by liyangwood** [comment]
@raindust 
If someone has debt, he can't bid, right?

**Comment by kevingzhang** [comment]
for this kind of error message. If possible, have a parameter showing how much TEA token required for this bid

**Comment by raindust** [comment]
> @raindust
> If someone has debt, he can't bid, right?

That's right

**Comment by kevingzhang** [comment]
1. Why someone has debt cannot bid? I do not get the reason.
2. If that is the case (I do not think it is), the error message doesn't tell the trust.

**Comment by raindust** [comment]
> for this kind of error message. If possible, have a parameter showing how much TEA token required for this bid

Substrate is not allowed to return errors with parameters, so there is no way to notice UI show this

**Comment by raindust** [comment]
> **User has enough TEA in wallet:**
>  ...

@geopor this happens when your bidding CML is still mining, you should not only pay for the bid price but also prepare enough free balance for the first slot (that would be 1000 TEA).

**Comment by kevingzhang** [comment]
this explanation makes sense. Can we have a better error message to explain this? I feel confused too if I were that user.

**Comment by kevingzhang** [comment]
for example, if just regular seeds(not mining), we can has the regular error message. but if that seeds is mining, we can have another error message.

**Comment by raindust** [comment]
ok, I will have a try

**Comment by raindust** [comment]
update in https://github.com/tearust/tea-camellia/commit/501311bb0ded0eb73495da221c788e2e5e23185c and https://github.com/tearust/tea-browser-wallet/commit/0c07ef51577e96d97e0fb6f38f07fb0c2c4b6333

**Comment by kevingzhang** [comment]
Could you assign this issue to @liyangwood so that he can continue the front end?

**Comment by raindust** [comment]
I already implemented the front end, no need to assign

**Comment by kevingzhang** [comment]
Please verify this issue because it is you who created it
