### ISSUE TITLE
My asset page UX enhancement

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#186]
![image](https://user-images.githubusercontent.com/12605218/129434025-4f3efc6f-151e-4d7e-b5eb-e4e54ae97305.png)

**Comment by liyangwood** [comment]
@kevingzhang 
is it confirmed to the wording changing. 
I think also change the Locked balance is better.

**Comment by kevingzhang** [comment]
What do you want to call "Locked balance". to "Locked TEA"?

**Comment by lxm218** [comment]
Locked TEA sounds better

**Comment by kevingzhang** [comment]
@geopor Please give your comments on the wording.

**Comment by liyangwood** [comment]
done with wallet version 0.0.43
