### ISSUE TITLE
Add unplant button. 

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#187]
@geopor , "unplant" is not an English word, what should we call the reverse of planting?

@liyangwood for mining CML , you can unplant it by set an icon here. 
![image](https://user-images.githubusercontent.com/1761809/129434759-8496d50d-a9dd-4f0c-96f5-2d40ea8d3942.png)

After unplant, the CML is in free mode. Free to sell. The locked deposit is unlock back to owner.

**Comment by liyangwood** [comment]
done with wallet version 0.0.43
@geopor 
Please check the wording.

**Comment by kevingzhang** [comment]
https://www.lexico.com/en/definition/unplant
It is called Unplant. Please update

**Comment by lxm218** [comment]
also change wording on this one:
![image](https://user-images.githubusercontent.com/12605218/129455627-f14df9d1-d296-4835-a62e-32ad325e3d03.png)

**Comment by liyangwood** [comment]
done
