### ISSUE TITLE
unplant issue: Unplant did not clear the debt

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#189]
1st screenshot shows before unplant
2nd screenshot shows after unplant
staking debt should be 0 in this case
![image](https://user-images.githubusercontent.com/12605218/129455828-11894e79-539d-4d2a-98d5-61f4747cca6c.png)
![image](https://user-images.githubusercontent.com/12605218/129455841-54fdbfd4-342e-4d64-b58d-add6ec733b26.png)

**Comment by kevingzhang** [comment]
this is a simple case.
The owner plant CML 476. It borrowed 994.5T and locked 5.5T. These two number total is 1000T. This is correct.
When unplant, all debt 994.5T is removed, remaining 5.5T unlock back to user account.. The total is still 1000T.
So in picture 2, the debt should be zero. But it still show 993.1438. 

This mistake cause this user owe 993.1438 T but it should not be.

**Comment by kevingzhang** [comment]
This is a backend bug, but @liyangwood FYI.

**Comment by raindust** [comment]
fixed in https://github.com/tearust/tea-camellia/commit/c5a0f8f31b9ec9f664048e1f6ec5aed20f125352
