### ISSUE TITLE
Possible change the UI text USD to COFFEE

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#190]
I got a few warning / suggestion from community. We probably would better not to use USD in our UI.

Although I do not think FBI will arrest me by misuse the USD, but it gives tester a wrong impression that USD is USD. 

Since we are not intent to refer to USD in our UI. We just trying to find a name rather than TEA as comparison, I would suggest we use the name COFFEE. I pick this name because Coffee is actually the competitor of TEA.

**Comment by kevingzhang** [comment]
@lxm218 @geopor @raindust what on your mind? any other better name to replace USD?

**Comment by lxm218** [comment]
BOBA

**Comment by kevingzhang** [comment]
BOBA is still a kind of TEA. 
We should use another kind of drink which compete with TEA. 
Coffee, Coke, Soda, Java etc.

If no other good name, we can use COFFEE

**Comment by liyangwood** [comment]
done to COFFEE
