### ISSUE TITLE
We allow negative number in total assets value, but the backend may return zero instead of negative number

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#192]
![image](https://user-images.githubusercontent.com/1761809/129607564-6878546b-05d1-4d77-84c6-e0f155c19d77.png)
@liyangwood I guess this is the backend RPC return value. 
If that is true, please send this to @raindust 
I know the Account type doesn't allow negative number, try to find other type

**Comment by liyangwood** [comment]
@kevingzhang 
confirmed the value 0 was returned by RPC interface.

@raindust 
Does Layer1 has the capability to return negative number?

**Comment by liyangwood** [comment]
done with wallet version 0.1.0
calculated in front-end
