### ISSUE TITLE
display major financial number in either position in My assets page

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#193]
![image](https://user-images.githubusercontent.com/1761809/129629763-88212341-244c-494d-add3-c55754775169.png)

Showing:
Genesis loan prime
Genesis loan interest rate
Coffee interest rate
TEA/Coffee exchange rate

The interest rate show in xx% in yy blocks

**Comment by liyangwood** [comment]
done with wallet version 0.1.0
