### ISSUE TITLE
Leader board show in two currency TEA and COFFEE

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#194]
Current we show in COFFEE. But user requests to have a two currency.

Please modify the header "Leader board(All assets are in USD value)" into -> "Leader board (All assets are in TEA, change to COFFEE?)"

If click "change to COFFEE", then change to COFFEE, and the text changed to "Leader board (All assets are in COFFEE, change to TEA?)"

Try to calculate on the front end.

FYI @raindust and @geopor @lxm218

**Comment by liyangwood** [comment]
done with wallet version 0.1.0

**Comment by kevingzhang** [comment]
![image](https://user-images.githubusercontent.com/1761809/129665719-b4c8f329-a93f-4321-bfd3-f87a7a5db378.png)
change the "change to COFFEE" a different color, so that people will know it can be clicked. otherwise, no one know they can click to change the unit

**Comment by kevingzhang** [comment]
It is better to change the (All asset....) whole line into the second line, smaller font, like subtitle

**Comment by kevingzhang** [comment]
Default is TEA, if user change to COFFEE, then COFFEE.

**Comment by lxm218** [comment]
(All assets are in TEA, click here to see in COFFEE) 

(All assets are in COFFEE, click here to see in TEA)

**Comment by liyangwood** [comment]
done with wallet version 0.1.1
