### ISSUE TITLE
add TApps List

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#196]
Add wallet.teaproject.org header "TApps". Click open a new page TApp list.

## TApp  list table

A table TApp list. Showing columns:
- TApp Name
- Token ticker symbol (hover for token ID)
- Token total supply
- Token buy price
- Token sell price
- Market cap : This number can be calculated at front end. Total supply * sell price
- Detail: One line text about this TApp. 
- Link:  a URL click to open new window to the TApp home page (likely outside of our webapp) 
- Action: Icons  Buy / Sell

Below the table. buttons:
- Create new TApp

## The New TApp modal:

- TApp name
- Token ticker symbol: Three to four letters allowed
- Detail: Text area. but recommend one line
- Link: URL
- Initial investment in TEA: Number. This is the number of TEA the creator can invest at the beginning
- Check box Accept the 100 bonus token? : By default checked. DAO will issue a few TApp token free of charge. This number may change during development/

Action button "Cancel" "Ok"

**Comment by liyangwood** [comment]
@raindust 

- TApp Name
- Token ticker symbol (hover for token ID)
- Token total supply
- Token buy price
- Token sell price
- Detail: One line text about this TApp.
- Link: a URL click to open new window to the TApp home page (likely outside of our webapp)

请在layer1补全上面这些字段，然后提供提供返回所有tapps的rpc或者query查询接口

**Comment by raindust** [comment]
implement in https://github.com/tearust/tea-camellia/blob/main/pallets/bounding-curve/rpc/src/lib.rs#L54-L66

**Comment by raindust** [comment]
add ticker in https://github.com/tearust/tea-camellia/commit/63bedf1a0cdbe027faa0757219186f3f6d88fe13

**Comment by liyangwood** [comment]
Deploy to the test-net
Url is http://139.198.27.87/

**Comment by kevingzhang** [comment]
Please use the names as they are in the issue comments:
> TApp Name
Token ticker symbol (hover for token ID)
Token total supply
Token buy price
Token sell price
Detail: One line text about this TApp.
Link: a URL click to open new window to the TApp home page (likely outside of our webapp)
请在layer1补全上面这些字段，然后提供提供返回所有tapps的rpc或者query查询接口

**Comment by liyangwood** [comment]
done in test-net
wallet version T_0.1.61
