### ISSUE TITLE
My invest TApps tab in My asset page

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#197]
We have a My invest Apps, change it to "My investment in TApps".

Show a table. Every row is a TApp the user invested in.

Table columns: 

- TApp Name
- Token ticker symbol (TokenId when hover)
- My holding tokens
- Token sell price
- My holding in TEA (based on sell price): calculated in front end
- Detail: One line text about this TApp. 
- Link: a URL click to open new window to the TApp home page (likely outside of our webapp)  
- Action: Icons Buy / Sell

**Comment by liyangwood** [comment]
@raindust 

- TApp Name
- Token ticker symbol (TokenId when hover)
- My holding tokens
- Token sell price
- My holding in TEA (based on sell price): calculated in front end
- Detail: One line text about this TApp.
- Link: a URL click to open new window to the TApp home page (likely outside of our webapp)

请看一下上面这些UI端需要的字段，需要在layer1端补全一下

然后这个用户所需要的tapps list应该是一个RPC的接口么？

**Comment by raindust** [comment]
implement in https://github.com/tearust/tea-camellia/blob/main/pallets/bounding-curve/rpc/src/lib.rs#L54-L66

**Comment by raindust** [comment]
implement in https://github.com/tearust/tea-camellia/commit/63bedf1a0cdbe027faa0757219186f3f6d88fe13

**Comment by liyangwood** [comment]
Deploy to the test-net
Url is http://139.198.27.87/
