### ISSUE TITLE
Buy / Sell TApp token modal

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#198]
When using click Buy / Sell TApp token from both TApp list page or the My investment in TApps tab, they go here.

You are [buying / selling] the token of [TApp name]'s token [Ticker symbol, eg. XYZ]. 
Amount in [TEA  / XYZ token]: number

When confirm, showing the second message box showing:

You will [pay NNN TEA / receive MMM XYZ]
Confirm button.

**Comment by liyangwood** [comment]
Deploy to the test-net
Url is http://139.198.27.87/
