### ISSUE TITLE
Auction bug deleting bids with CML seed 186

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#199]
Was notified that CML 186 couldn't have bids deleted. It was a seed put up for auction by the SUDO account 5Eo1WB2ieinHgcneq6yUgeJHromqWTzfjKnnhbn43Guq4gVP

<img width="1120" alt="2 Auction" src="https://user-images.githubusercontent.com/86096370/130467916-9b5f5cf4-09be-4e98-8e38-37376fd8f6f1.png">

<img width="515" alt="1" src="https://user-images.githubusercontent.com/86096370/130467919-d84e55b6-a992-4c0a-a750-22a83e4eb9a6.png">

Does show status as staking to CML 188:

<img width="1119" alt="3 detail" src="https://user-images.githubusercontent.com/86096370/130467998-0b3e26f2-4836-415c-ab98-54553d119616.png">

Confirmed in detail page:

<img width="1134" alt="4 staking" src="https://user-images.githubusercontent.com/86096370/130467993-3e1ae76c-2721-4744-bfda-1522e2de5502.png">

 But doesn't show up in sudo's staking page:

<img width="1102" alt="5" src="https://user-images.githubusercontent.com/86096370/130468055-7d7754f0-09c8-48b4-8f25-ac25b7519866.png">

And all auctions should still appear in seller's wallet until auction completed, but it's not here either:

<img width="1108" alt="6" src="https://user-images.githubusercontent.com/86096370/130468044-5ce35a13-f449-4de1-a863-a29d78625509.png">

**Comment by kevingzhang** [comment]
this could be a backend bug @raindust  Please take a look. If confirmed, please resigned to yourself.

**Comment by liyangwood** [comment]
@raindust  please have a look

**Comment by raindust** [comment]
not yet, it's just the implementation idea for discussion

**Comment by raindust** [comment]
> fixed in [tearust/tea-camellia@f8695eb](https://github.com/tearust/tea-camellia/commit/f8695eb3b61de14ab7b56b4b1f3304641b12a431)

already fixed, @kevingzhang you can verify it in the testnet, I mistake with other issue
