### ISSUE TITLE
Active bids - change unit of measure

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#201]
Active bids unit of measure is currently **Unit**:

<img width="983" alt="Screen Shot 2021-08-23 at 7 37 32 AM" src="https://user-images.githubusercontent.com/86096370/130472499-3567e757-edd8-4ccb-8f17-3f472bbf72f8.png">

Should change to look like this: 

<img width="983" alt="changed" src="https://user-images.githubusercontent.com/86096370/130473028-dac041ff-0c20-4ef6-9e32-a3e8d16875b5.png">

**Comment by liyangwood** [comment]
done in test-net
wallet version T_0.1.61
