### ISSUE TITLE
Modal dialog - Unplant CML

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#202]
For the following unplant CML modal dialog:

<img width="1184" alt="Screen Shot 2021-08-24 at 10 39 02 AM" src="https://user-images.githubusercontent.com/86096370/130672637-a250006f-3f72-4c4b-9a5a-4398147e4e89.png">

It should read:

Are you sure you want to unplant this CML?
Please **note** that **you'll** need to compensate each staker 100 TEA.

**Comment by liyangwood** [comment]
done in testnet
