### ISSUE TITLE
UX confusion - why did planting CML fail?

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#204]
This was user **sudo**'s wallet at the beginning of this trancaction:

<img width="1181" alt="Screen Shot 2021-08-24 at 10 21 05 AM" src="https://user-images.githubusercontent.com/86096370/130674488-c38b783c-76e3-4150-b1cb-b8a6325cfaec.png">

Tried to stake to a mining machine (testnet) and failed although I had 500 COFFEE. 

<img width="1136" alt="Screen Shot 2021-08-24 at 10 22 42 AM" src="https://user-images.githubusercontent.com/86096370/130674379-895471a2-f7dc-4302-b807-1fa6b0778cfe.png">

It didn't go through even though I had more than 500 COFFEE. Eventually it went through when I had 1000 TEA in the account.

### Suggestion

The dialog doesn't say which balance is insufficient. I would suggest specifying whether the user needs more TEA or COFFEE (or both).

**Comment by liyangwood** [comment]
Reason is plant a cml need 1000 TEA to stake as the first slot.

@geopor 
Could you change the wording in plant page to let user clear  that need 1000 TEA to stake?
