### ISSUE TITLE
UX - Add columns to Marketplace auctions

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#205]
These would be for the various auction screens at https://wallet.teaproject.org/#/auction_store

## 1. Include a "Type" column 

Right now you have to click through to find out what kind of seed it is. 

<img width="1110" alt="Screen Shot 2021-08-23 at 8 30 05 AM" src="https://user-images.githubusercontent.com/86096370/130476199-ae42bae4-42b8-43cd-b03d-4990613d2486.png">

## 4. Include a "Current / peak performance" column

**Comment by liyangwood** [comment]
done in test-net.
