### ISSUE TITLE
Have enough COFFEE, but cannot plant CML

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#206]
![image](https://user-images.githubusercontent.com/12605218/130720371-7c36e336-f7d2-4c8c-bafb-7a0ade2eb320.png)

![image](https://user-images.githubusercontent.com/12605218/130720428-c92e2c09-6e47-41a0-8a40-1077854724d7.png)

**Comment by kevingzhang** [comment]
this is not a bug
