### ISSUE TITLE
If you have any new error message, always create the error message string and ask George to review

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#208]
![image](https://user-images.githubusercontent.com/1761809/130825976-cca8facd-f2a1-4e07-bd1f-87b342f973a5.png)

Please do this for all error messages and future changes.

**Comment by geopor** [comment]
@kevingzhang Not really sure what **OnlyTAppOwnerAllowedToExpense** refers to, I translated literally https://github.com/tearust/tea-browser-wallet/commit/ab003a3f2b693e28cb4941dcb6e2ec2e73463c17

**Comment by kevingzhang** [comment]
It is what it literally is. it doesn't matter since in the real TApp, people will not see this error message. The expense is done at the backend. Usually payment to the host miners periodically. Right now we have such a button to test purpose.
