### ISSUE TITLE
Bug: Can list same CML multiple times

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#209]
**Bug**: can start multiple auctions for the same CML seed id. First saw this in **sudo** account, confirmed also in **vitalik** account:

<img width="1128" alt="Screen Shot 2021-08-25 at 12 44 26 PM" src="https://user-images.githubusercontent.com/86096370/130856364-060bade1-3549-4b63-b93e-8b29d94cfb5b.png">

## Another example, double listing of CML 539
- **vitalik** double lists **CML 539**
- first listing is bought by **5Hg6MasMWxV63uACSqTJQ8Yv1swpiZN1X6LqVQ6QeZEL9sqP**
- That listing disappears because it's been sold
- But the other CML 539 listing is still open and shows the new owner mining it:

<img width="1144" alt="Screen Shot 2021-08-25 at 1 26 08 PM" src="https://user-images.githubusercontent.com/86096370/130860314-03ecec59-79bb-459c-aa94-0c400be05f4e.png">

This is obviously a problem because **vitalik** is selling a seed he no longer owns.

Now let's see what happens when **trump** tries to buy the second listing:

<img width="418" alt="Screen Shot 2021-08-25 at 1 28 23 PM" src="https://user-images.githubusercontent.com/86096370/130860731-d6705eb2-8827-4392-a04f-7b1cf88d88cc.png">

**Comment by raindust** [comment]
fixed in https://github.com/tearust/tea-camellia/commit/47f5c6f83052d56544e1cde847007dae26688676
