### ISSUE TITLE
This CML is in auction, but it has 1000T staking on it, the bid price here doesn't really reflect real price bidder needs to pay

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#211]
I suggest to include staking into bid price

![image](https://user-images.githubusercontent.com/12605218/131016782-a1a04f5a-3e01-4768-bad2-20d0788d547f.png)

![image](https://user-images.githubusercontent.com/12605218/131016871-d62fe741-ff5c-4c61-9fd2-78c52be33df6.png)

![image](https://user-images.githubusercontent.com/12605218/131017091-6d0d0f8d-a269-4ebb-a763-7ed447f8665b.png)

**Comment by kevingzhang** [comment]
Please hold this issue under your name. We can fix it after epoch 2.5

**Comment by raindust** [comment]
fixed in https://github.com/tearust/tea-internal/issues/200

**Comment by liyangwood** [comment]
done in test-net
