### ISSUE TITLE
Error message mention USD, should it be COFFEE here?

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#214]
![image](https://user-images.githubusercontent.com/12605218/131266970-a8fa87cb-998b-42d8-a0ed-b8043cefd910.png)

**Comment by liyangwood** [comment]
done in testnet

**Comment by lxm218** [comment]
![image](https://user-images.githubusercontent.com/12605218/131380501-1f7aa743-92f4-492c-b831-eada50e9fa27.png)

**Comment by liyangwood** [comment]
done in testnet
