### ISSUE TITLE
UX: Tooltips / explanation text especially for new epoch 3 features

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#216]
These are all tooltip / hover / explanatory text to help improve the user experience.

<img width="1126" alt="Screen Shot 2021-08-31 at 4 40 53 PM" src="https://user-images.githubusercontent.com/86096370/131589726-a911b9a1-f7db-4d65-af0c-bc869d56197d.png">

### :hover tips
1. **Top up** 
> Receive 0.1 TEA to help pay transaction fees
2. **Withdraw reward** 
> Send your staking reward to your TEA wallet balance
3. **Borrow COFFEE**
> Borrow COFFEE at the interest rate listed below

**Comment by geopor** [comment]
<img width="1155" alt="Screen Shot 2021-08-31 at 4 51 35 PM" src="https://user-images.githubusercontent.com/86096370/131590330-af388f28-5c94-4937-a706-86af856be907.png">

**Miner Id**
_tooltip:_ 
> A name for your mining machine (must be unique)

**Miner IP** _note, IP should have both letters capitalized_
_tooltip:_ 
> The IP address of your mining machine (can be anything - not checked during contest)

**Comment by geopor** [comment]
## Deposit CML for loan
<img width="977" alt="Screen Shot 2021-08-31 at 4 14 26 PM" src="https://user-images.githubusercontent.com/86096370/131590624-cebcabd1-8e48-499f-9b49-fd641d6b696b.png">

1. Interest rate should be changed in both places, it's currently .1 % in the testing wallet.
2. In the first paragraph of the **Loan Repayment** section, the following sentence should be added:
Paying the outstanding interest due will renew the loan for another term.

**Comment by geopor** [comment]
### TApps tab
If there's no room for a **?** tooltip then maybe we can show this information using **:hover** css?

<img width="1170" alt="Screen Shot 2021-08-31 at 5 03 45 PM" src="https://user-images.githubusercontent.com/86096370/131591273-78896318-c81a-49f4-9b02-b36e4307a650.png">

1. Total supply
> Total number of tokens issued

2. Buy price (TEA)
> Price at which you can buy the token from the bonding curve

3. Sell price (TEA)
> Price at which you can sell the token into the bonding curve

4. Market cap
> The current sell price multiplied by the number of tokens outstanding

5. Host performance requirement
> A mining machine must be at least this powerful to host this TApp

6. Current / Max hosts
> The maximum number of hosts that can be hosting this TApp

7. Actions
> You can buy or sell the TApp's token, and host (or unhost) the TApp

**Comment by liyangwood** [comment]
done in test net
