### ISSUE TITLE
UI bug - must push + or - button to accept the number

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#217]
Just noticed this bug in two places:
1. When trying to borrow COFFEE
2. When buying TApp tokens

If I enter a number, it gives red error message:

<img width="995" alt="Screen Shot 2021-08-31 at 1 57 04 PM" src="https://user-images.githubusercontent.com/86096370/131592067-d7b52457-78b7-41f0-a6fa-f8fb881d6a03.png">

<img width="991" alt="Screen Shot 2021-08-31 at 2 32 31 PM" src="https://user-images.githubusercontent.com/86096370/131592072-248e468c-c5c1-41ae-9cbe-7a1ad2808679.png">

Only when I push the + or - button does it let me proceed:

<img width="982" alt="Screen Shot 2021-08-31 at 1 57 21 PM" src="https://user-images.githubusercontent.com/86096370/131592071-8c667fbb-c4de-4bfb-a639-52129a6001ed.png">

**Comment by geopor** [comment]
Correction, it looks like you can proceed even if it says error message

**Comment by liyangwood** [comment]
Yeah, that is the InputNumber component behaviour, the validate only occurred when input lost focus.

I change it and only validate when click the confirm button.
done in test-net.
