### ISSUE TITLE
UX: Tooltips / explanation text - Planting CML

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#218]
<img width="1155" alt="Screen Shot 2021-08-31 at 4 51 35 PM" src="https://user-images.githubusercontent.com/86096370/131590330-af388f28-5c94-4937-a706-86af856be907.png">

**Miner Id**
_tooltip:_ 
> A name for your mining machine (must be unique)

**Miner IP** _note, IP should have both letters capitalized_
_tooltip:_ 
> The IP address of your mining machine (can be anything - not checked during contest)

**Comment by liyangwood** [comment]
done in testnet
