### ISSUE TITLE
UX: Tooltips / explanation text - Deposit CML for loan

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#219]
## Deposit CML for loan
<img width="977" alt="Screen Shot 2021-08-31 at 4 14 26 PM" src="https://user-images.githubusercontent.com/86096370/131590624-cebcabd1-8e48-499f-9b49-fd641d6b696b.png">

1. Interest rate should be changed in both places, it's currently .1 % in the testing wallet.
2. In the first paragraph of the **Loan Repayment** section, the following sentence should be added:
Paying the outstanding interest due will renew the loan for another term.

**Comment by geopor** [comment]
Hi @liyangwood 
@lxm218 just mentioned something that I overlooked:

The current line that reads:
**The current loan amount is 500T regardless of the type of seed used for collateral.**

That should be changed to:

> The current loan amount depends on the type of seed used for collateral: 2000T for A seeds, 1000T for B seeds, and 500T for C seeds.**

**Comment by lxm218** [comment]
The last sentence in the Loan Repayment section needs to be updated.

**Comment by liyangwood** [comment]
done in test-net
