### ISSUE TITLE
UX: Tooltips / explanation text - TApps tab

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#220]
### TApps tab
If there's no room for a **?** tooltip then maybe we can show this information using **:hover** css?

<img width="1170" alt="Screen Shot 2021-08-31 at 5 03 45 PM" src="https://user-images.githubusercontent.com/86096370/131591273-78896318-c81a-49f4-9b02-b36e4307a650.png">

1. Total supply
> Total number of tokens issued

2. Buy price (TEA)
> Price at which you can buy the token from the bonding curve

3. Sell price (TEA)
> Price at which you can sell the token into the bonding curve

4. Market cap
> The current sell price multiplied by the number of tokens outstanding

5. Host performance requirement
> A mining machine must be at least this powerful to host this TApp

6. Current / Max hosts
> The maximum number of hosts that can be hosting this TApp

7. Actions
> You can buy or sell the TApp's token, and host (or unhost) the TApp

**Comment by kevingzhang** [comment]
there is no way to add tooltip in the table head. you have to find another way

**Comment by kevingzhang** [comment]
@geopor think about the legend or something else?

**Comment by geopor** [comment]
## TApps tab

Ok legend can look like this:

<img width="1170" alt="Screen Shot 2021-08-31 at 5 03 45 PM" src="https://user-images.githubusercontent.com/86096370/131932991-398fdeaf-5e07-43ea-829b-c39ec98e905d.png">

## Text of the legend with wiki links
- The [token supply](https://github.com/tearust/teaproject/wiki/Epoch-3-TApps-List#total-supply) and [token price](https://github.com/tearust/teaproject/wiki/Epoch-3-TApps-List#buy-price) are determined by [the bonding curve](https://github.com/tearust/teaproject/wiki/Epoch-3-TApps-List#sell-price).

- The [host performance requirement](https://github.com/tearust/teaproject/wiki/Epoch-3-Mining#host-performance-requirement) is the minimum power required for a mining machine to host this TApp.

- [Current / max hosts](https://github.com/tearust/teaproject/wiki/Epoch-3-Mining#current-and-max-hosts) is the maximum number of CML miners that can be hosting this TApp.

- In the **actions** section, you can buy or sell the TApp's token as well as [host (or unhost) the TApp](https://github.com/tearust/teaproject/wiki/Epoch-3-Mining#host-and-unhost-tapp).

**Comment by kevingzhang** [comment]
@geopor you can assign the ui issue to jacky directly.

**Comment by liyangwood** [comment]
done in https://wallet.teaproject.org/
