### ISSUE TITLE
Text change for Borrow COFFEE modal

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#221]
For **Borrow COFFEE** modal dialog:

<img width="648" alt="Screen Shot 2021-09-04 at 12 17 27 AM" src="https://user-images.githubusercontent.com/86096370/132086759-f4e58eb4-39f7-4d57-9fed-54bf11972af7.png">

Please change as shown in the above picture and add a sentence with the wiki link:

**Borrow COFFEE**
The COFFEE interest rate is 0.1% per 100 blocks.
You can borrow at most 2632288.724 COFFEE.
More info about COFFEE interest compounding is available [on our wiki](https://github.com/tearust/teaproject/wiki/Epoch-3-COFFEE#coffee-loans).

**Comment by liyangwood** [comment]
done with epoch 3.1
