### ISSUE TITLE
Text change for Top up (faucet)

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#222]
When users click the **Top up** button, they go to this faucet page: http://198.199.82.222:2900/#/

The text at the top there should be changed to:

**Faucet**
Please input your account address and click the confirm button.
For more info on what the faucet is used for, [visit our wiki](https://github.com/tearust/teaproject/wiki/Epoch-3-TEA-Loans#top-up).

**Comment by liyangwood** [comment]
done with epoch 3.1
