### ISSUE TITLE
Text change for Genesis Loan modal

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#223]
The text at the top of the Genesis Loan modal should be changed.

<img width="756" alt="Screen Shot 2021-09-04 at 1 01 51 AM" src="https://user-images.githubusercontent.com/86096370/132087562-a3f54933-645a-42a1-97fe-4a594572fac6.png">

It should read:

**Deposit CML for loan**
Are you sure you want to deposit CML as collateral for a Genesis loan? For more info on how to use these loans, [visit our wiki](https://github.com/tearust/teaproject/wiki/Epoch-3-TEA-Loans#genesis-tea-loans).

**Comment by liyangwood** [comment]
done with epoch 3.1
