### ISSUE TITLE
Text change for host/unhost TApp

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#224]
For the host/unhost TApp modal:

<img width="1007" alt="Screen Shot 2021-09-04 at 1 07 16 AM" src="https://user-images.githubusercontent.com/86096370/132087742-28847052-ff84-4cae-83ee-364bf5806f17.png">

There should now be added a new sentence with a link to our wiki.

>ETH Node requires 500 performance to host. Please select one of the CML which is qualified to host.
> For more info about maximizing your hosting revenue, [visit our wiki](https://github.com/tearust/teaproject/wiki/Epoch-3-Mining#host-and-unhost-tapp).

**Comment by liyangwood** [comment]
done with epoch 3.1
