### ISSUE TITLE
Text change for TApp bonding curve token buy button

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#225]
For the **Buy** button when buying a TApp's token, modal looks like this:

<img width="582" alt="Screen Shot 2021-09-04 at 1 19 45 AM" src="https://user-images.githubusercontent.com/86096370/132088239-663296ad-964b-4bc3-a355-680e1d9e3d4e.png">

This should be changed to:

> You are buying the tokenomic's token ECO. For more information on how to invest in TApp tokens, [visit our wiki](https://github.com/tearust/teaproject/wiki/Epoch-3-TApps-List#tapp-token-strategy).

**Comment by liyangwood** [comment]
done with epoch 3.1
