### ISSUE TITLE
Text change for Plant my Camellia

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#226]
For planting a Camellia into a mining machine, the modal dialog should be changed. 

<img width="1121" alt="Screen Shot 2021-09-04 at 1 40 14 AM" src="https://user-images.githubusercontent.com/86096370/132088591-52d540fe-94e4-4c6b-b522-4f7c5dd14b8f.png">

The highlighted sentence above should be changed to:

> Note that you need 500 COFFEE to buy a mining machine and 1000 TEA available for your initial stake. More info is available [on our wiki](https://github.com/tearust/teaproject/wiki/Epoch-3-Mining#mining-machines-are-no-longer-free).

**Comment by liyangwood** [comment]
done with epoch 3.1
