### ISSUE TITLE
Text: TApp no longer accepting hosts

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#227]
For the following:

<img width="1018" alt="Screen Shot 2021-09-07 at 9 41 23 AM" src="https://user-images.githubusercontent.com/86096370/132606930-009c81fb-89b5-4d98-99e7-80f81c24ac6a.png">

The text should read:

> This TApp no longer accepts new hosts

**Comment by liyangwood** [comment]
done to epoch 3.4
