### ISSUE TITLE
Text on Leader board for registration onboarding

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#228]
When users go to https://wallet.teaproject.org/#/leader_board and click to join the contest, instead of 

<img width="966" alt="Screen Shot 2021-09-08 at 4 55 32 PM" src="https://user-images.githubusercontent.com/86096370/132607134-971ad27b-80fe-4385-8945-43ec702f4e4e.png">

Instead of **Account**, it should read **Polkadot{.js} address**:

<img width="615" alt="Screen Shot 2021-09-08 at 5 10 40 PM" src="https://user-images.githubusercontent.com/86096370/132607177-4e43c0be-a74e-4f08-bcb3-30ba15b27bdd.png">

**Comment by liyangwood** [comment]
done to epoch3.4
