### ISSUE TITLE
TApps Tab - Add explainer text

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#229]
At the end of the highlighted sentence we should add another sentence:

<img width="1151" alt="Screen Shot 2021-09-10 at 12 06 06 PM" src="https://user-images.githubusercontent.com/86096370/132904948-bab8332d-b391-4a15-9070-6606613ad789.png">

> Your TApp tokens in your wallet will expand or contract based on [consume and expense actions](https://github.com/tearust/teaproject/wiki/Epoch-3-TApps-List#tapp-tokens-in-wallet-expand-on-consume-contract-on-expense) on the TApp's bonding curve.

It should look like this afterwards:

<img width="636" alt="Screen Shot 2021-09-10 at 12 15 29 PM" src="https://user-images.githubusercontent.com/86096370/132905722-1887a51d-3ff9-4ab6-ae54-ecee376d3a47.png">

**Comment by liyangwood** [comment]
done
