### ISSUE TITLE
Epoch 4 Test Wallet - can't select account to login

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#231]
**Not able to select account in upper right:**

![Screen Shot 2021-09-22 at 4 39 23 PM (2)](https://user-images.githubusercontent.com/86096370/134436782-b4c5ef4b-8504-445c-be9a-179738222c10.png)

**Comment by raindust** [comment]
Please help @geopor

**Comment by geopor** [comment]
sorted, thanks
