### ISSUE TITLE
Design a welcome page

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-browser-wallet#41]
![image](https://user-images.githubusercontent.com/1761809/124642711-01d86280-de45-11eb-8804-3064d2055dd4.png)

**Comment by geopor** [comment]
## The TEA Browser Wallet

- Make sure you've installed the polkadot{.js} browser extension. It's available for [Chrome](https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd), [Brave](https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd), and [Firefox](https://addons.mozilla.org/en-US/firefox/addon/polkadot-js-extension/).

- You can use your TEA browser wallet to earn TEA tokens through mining or staking. Mining TEA requires planting a Camellia (CML) NFT into a mining machine and paying [//TEA]1000 for the initial staking slot. Staking can be done on any mining machine operating on the TEA network. Each staking slot requires either [//TEA]1000 or 1 CML. You may stake or unstake every 1000 blocks.

- More help is available in [the mining and staking guide](https://teaproject.org/#/doc_list/Try_the_demo%2FREADME.md) on our website.

- Learn more about the TEA Project on [our website](https://teaproject.org). You can also visit us on - [YouTube](https://www.youtube.com/channel/UChYmd52JIe0zTdIdXHLK7WQ), [Twitter](https://twitter.com/teaprojectorg/), and [Telegram](t.me/teaprojectorg).

**Comment by kevingzhang** [comment]
we can use this as the starting point. then fill up more help information step by step. Once there are real users start using it, there would be question to be answered. we will know what they ask and add the FAQ here. Please send it to Jacky and add to the welcome page

**Comment by geopor** [comment]
@kevingzhang ok can you change my permissions on this repo, I can't assign issues right now

**Comment by kevingzhang** [comment]
@liyangwood please complete this welcome page asap

**Comment by liyangwood** [comment]
Done with wallet version 0.0.14
