### ISSUE TITLE
Fix some wordings

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#96]
1. User Sudo tried to pay off staking debt
2. Pop up message shows below:

Change to: Your staking debt will be paid off in full. Are you sure you want to continue?

![image](https://user-images.githubusercontent.com/12605218/125677768-1c013f99-13dd-42bf-b99a-ef24705e9d7c.png)

**Comment by liyangwood** [comment]
duplicate with George's issue. 
it could be closed
